# Assignment 3 - Question 2

In [2]:
import pandas as pd
import os
import numpy as np

In [28]:
d = pd.read_csv("IMDB_data.csv", encoding="cp1252")
d
#works fine even with encoding = 'iso-8859-1', 'cp1252', 'iso-8859-15', 'latin1'
#gives error on encoding = 'utf-8', 'utf-16'

,Plot,Title,imdbVotes,Poster,imdbRating,Genre,imdbID,Year,Language
0,Despite his tarnished reputation after the eve...,The Dark Knight Rises,2679,http://ia.media-imdb.com/images/M/MV5BMTk4ODQz...,75,"Action, Thriller",tt1345836,2012,English
1,0,0,0,0,0,0,0,0,0
2,"Based on the novel written by Stephen Chbosky,...",The Perks of Being a Wallflower,1270,http://ia.media-imdb.com/images/M/MV5BMzIxOTQy...,71,"Drama, Romance",tt1659337,2012,English
3,Mike Lane is a thirty-year old living in Tampa...,Magic Mike,2580,http://ia.media-imdb.com/images/M/MV5BMTQzMDMz...,51,"Comedy, Drama",tt1915581,2012,English
4,When Bond's latest assignment goes gravely wro...,Skyfall,1807,http://ia.media-imdb.com/images/M/MV5BMjAyODkz...,68,"Action, Thriller",tt1074638,2012,English
5,Against medical advice and without the knowled...,Silver Linings Playbook,1828,http://ia.media-imdb.com/images/M/MV5BMTM2MTI5...,68,"Comedy, Drama, Romance",tt1045658,2012,English
6,A shy senior and a down-to-earth junior fall i...,The First Time,1538,http://ia.media-imdb.com/images/M/MV5BMjMxNDI1...,60,"Comedy, Drama, Romance",tt1763303,2012,English
7,"In California, the former Navy SEAL Chon and h...",Savages,2683,http://ia.media-imdb.com/images/M/MV5BMTk0ODIy...,55,"Crime, Drama, Thriller",tt1615065,2012,English
8,Meet the Borgens. William Borgens is an acclai...,Stuck in Love,1832,http://ia.media-imdb.com/images/M/MV5BMTU1NzI5...,63,"Comedy, Drama, Romance",tt2205697,2012,English
9,"In 1874, in the Imperial Russia, the aristocra...",Anna Karenina,2094,http://ia.media-imdb.com/images/M/MV5BMTU0NDgx...,56,"Drama, Romance",tt1781769,2012,English
10,"In the 1960s, Richard Kuklinski is working as ...",The Iceman,1859,http://ia.media-imdb.com/images/M/MV5BNDQyMjM5...,59,"Biography, Crime, Drama",tt1491044,2012,English
11,The sunrise blinds the early risers of the cit...,Broken Ledge,2718,http://ia.media-imdb.com/images/M/MV5BMTcyMzYz...,87,Drama,tt2508268,2012,English
12,A mysterious traveler infiltrates a dangerous ...,In the Realms of Madness,2718,http://ia.media-imdb.com/images/M/MV5BNzA2NzE3...,87,"Drama, Horror",tt2248841,2012,English
13,"In both its story on and off the screen, 'Flan...",Flaneurs,2718,NaN,87,"Drama, Romance",tt2364671,2012,English
14,Hailey is in an unhappy marriage but she devel...,The Start of Something Good,2718,NaN,87,"Drama, Romance",tt2331062,2012,English
15,Yannick has to deal with the haunting by himse...,True Storys of the Ghost House 3 the Demon Phe...,2718,NaN,87,Horror,tt3098520,2012,English
16,Seduced by the haunting beauty of a remote mar...,White Wind,2718,NaN,87,"Drama, Mystery",tt2555620,2012,English
17,A psychotic Iraq War veteran teaches his young...,Thelema the Equinox Diaries,2718,NaN,87,"Drama, Thriller",tt2443106,2012,English
18,A politician receives a message that his mistr...,Home Minister,2718,NaN,87,Drama,tt2923826,2012,English
19,A plot to assassinate the Vice President takes...,Placebo Effect,1752,http://ia.media-imdb.com/images/M/MV5BMTU5Njg1...,52,"Crime, Mystery, Thriller",tt0163154,1998,English
20,Long on the Island is a psychological thriller...,Long on the Island,2718,NaN,87,"Fantasy, Horror",tt2375263,2012,English
21,"Over the course of a single night, Dave and An...",I Did,2718,NaN,87,"Drama, Family",tt2388672,2012,English
22,"""Collaging Film"" is a series of shorts dating ...",Collaging Film,2718,NaN,87,Animation,tt4416372,2012,English
23,Hank lives the quiet life until a mysterious i...,Welcoming Departure,2718,http://ia.media-imdb.com/images/M/MV5BMjE0OTU2...,87,"Comedy, Drama",tt2235809,2012,English
24,The Luckiest Girl on the Lower East Side takes...,The Luckiest Girl on the Lower East Side,2718,NaN,87,Drama,tt1876494,2012,English
25,"Less Lost, is the fictional story of a young m...",Less Lost,1114,http://ia.media-imdb.com/images/M/MV5BMTk3MTg2...,68,"Drama, War",tt2259946,2012,English
26,High school student Aidan loses his girlfriend...,Still Here,2302,NaN,53,Drama,tt2275650,2012,English
27,Best friends Sam and Mike go out on a bender a...,The Hedgehog Dilemma,2718,http://ia.media-imdb.com/images/M/MV5BMTU1NDI3...,87,"Drama, Romance",tt2505274,2012,English
28,Filmed and produced by Australian director Sha...,51 Paintings,2457,http://ia.media-imdb.com/images/M/MV5BMTQyNzU2...,61,Drama,tt2318982,2012,English
29,"Capitalists, revolutionaries, and the people w...",The Adventures of Paul and Marian,2718,NaN,87,"Comedy, Musical, Romance",tt1949593,2012,English
...,...,...,...,...,...,...,...,...,...
3360,Prabhavati lives a wealthy lifestyle in India ...,Sneham Kosam,NaN,NaN,6.3,"Family, Action",tt0246240,1999,Telugu
3361,The story of the famous Saint-Poet Manjunatha.,Sri Manjunatha,NaN,NaN,6.7,"Drama, Family, History, Musical",tt0249783,2001,Telugu
3362,Lord Rama's life is one of perfect adherence t...,Sri Rama Rajyam,635,NaN,7.2,Drama,tt1783377,2011,Telugu
3363,Based on the life story of the great devotee-m...,Sri Ramadasu,207,NaN,6.9,"Biography, Musical",tt0459205,2006,Telugu
3364,Josef Stalin rises from his rejection as being...,Stalin,653,http://ia.media-imdb.com/images/M/MV5BMTk5OTQw...,5.6,"Action, Drama",tt0105462,2006,Telugu
3365,"The story of aspiring police officer, Prithvir...",State Rowdy,68,NaN,7.4,"Action, Crime, Drama",tt0246254,1989,Telugu
3366,Aditya lives a middle-classed lifestyle in Aur...,Student No 1,473,NaN,6.7,"Action, Crime, Drama",tt1283956,2001,Telugu
3367,Bantu and Chantu are two close friends and fel...,Style,NaN,NaN,5.8,Musical,tt0306855,2006,Telugu
3368,Amarchandra lives a poor lifestyle in British ...,Subhash Chandra Bose,NaN,NaN,2.9,"Action, Drama, History, Romance, Thriller",tt0459554,2005,Telugu
3369,Frank Darrbo is a hapless fry cook. When his w...,Super,NaN,http://ia.media-imdb.com/images/M/MV5BMTcxMDkx...,5.1,"Action, Comedy, Drama, Mystery, Romance",tt1512235,2005,Telugu
3370,Unable to convince the ruling council of Krypt...,Superman,49,http://ia.media-imdb.com/images/M/MV5BMTI1MjA5...,4.2,"Fantasy, Musical, Sci-Fi",tt0078346,1980,Telugu
3371,A priceless idol is stolen from a temple trave...,Swamy Ra Ra,443,NaN,7.5,Crime,tt2767354,2013,Telugu
3372,"The story of a classical singer, who finds it ...",Swathi Kiranam,NaN,NaN,7.8,"Family, Musical, Drama",tt0250012,1992,Telugu
3373,"Ravindranath Tagore, A physics professor forms...",Tagore,861,NaN,7.6,"Action, Drama",tt0361037,2003,Telugu
3374,"Raja is a small-time outlaw, whose daring anti...",Takkari Donga,644,NaN,6.9,"Action, Adventure, Western",tt0307541,2002,Telugu
3375,The story of an Indian Freedom fighter who fou...,Tandra Paparayudu,61,NaN,8,"Action, Biography, Drama, History",tt0253784,1986,Telugu
3376,"Raghu, a business tycoon, is driving through a...",Tarzan Sundari,7,NaN,6,"Action, Adventure, Fantasy, Musical",tt2735328,1983,Telugu
3377,A man reconsiders his ideas about love in the ...,Teen Maar,909,NaN,5.8,"Comedy, Drama, Romance",tt1889440,2011,Telugu
3378,Daya (NTR) is a fully corrupted police officer...,Temper,"1,331",NaN,8.1,"Action, Drama",tt4442758,2015,Telugu
3379,Classic about the life story of Carnatic Music...,Thyagayya,NaN,NaN,7.3,"Family, History, Musical",tt0246277,1946,Telugu
3380,"A romantic entertainer between a ""bava"" and a ...",Uyyala Jampala,NaN,NaN,7.5,"Drama, Family, Romance",tt3290676,2013,Telugu
3381,About to re-locate to the U.S. but refusing to...,Varudu,438,NaN,3.5,"Action, Crime, Drama, Thriller",tt1582637,2010,Telugu
3382,Cable Raju is a slum dweller who works as a ca...,Vedam,"2,015",NaN,8.1,Drama,tt1649431,2010,Telugu
3383,A simple train journey to Tirupathi goes horri...,Venkatadri Express,79,NaN,7.5,"Adventure, Comedy",tt3573040,2013,Telugu
3384,Venky and his friends are accused of murdering...,Venky,NaN,NaN,7.1,"Mystery, Romance",tt0417229,2004,Telugu
3385,"Vikram Rathod, A sincere Police man joins with...",Vikramarkudu,"1,158",NaN,7.5,"Action, Comedy, Crime, Thriller",tt0858492,2006,Telugu
3386,After an eventful train trip on the Visakha/Ra...,Visakha Express,43,NaN,4.5,"Crime, Drama, Mystery, Thriller",tt1285147,2008,Telugu
3387,"Mahi is a beautiful wealthy heiress, but her f...",Yamadonga,"1,316",NaN,7.3,"Action, Comedy, Fantasy, Romance",tt0924317,2007,Telugu
3388,Yevade Subramanyam has wrapped its shooting an...,Yevade Subramanyam,188,NaN,7.9,"Adventure, Comedy, Drama",tt4515070,2015,Telugu
3389,Sathya (Allu Arjun) returns from a coma to tak...,Yevadu,"3,966",NaN,4.6,"Action, Thriller",tt2211173,2014,Telugu

In [26]:
#==================  2a  =====================
dataIMDB = pd.read_csv("IMDB_data.csv", header = [0], encoding = "ISO-8859-15", skiprows = [2])
dataIMDB

,Plot,Title,imdbVotes,Poster,imdbRating,Genre,imdbID,Year,Language
0,Despite his tarnished reputation after the eve...,The Dark Knight Rises,2679,http://ia.media-imdb.com/images/M/MV5BMTk4ODQz...,75,"Action, Thriller",tt1345836,2012,English
1,"Based on the novel written by Stephen Chbosky,...",The Perks of Being a Wallflower,1270,http://ia.media-imdb.com/images/M/MV5BMzIxOTQy...,71,"Drama, Romance",tt1659337,2012,English
2,Mike Lane is a thirty-year old living in Tampa...,Magic Mike,2580,http://ia.media-imdb.com/images/M/MV5BMTQzMDMz...,51,"Comedy, Drama",tt1915581,2012,English
3,When Bond's latest assignment goes gravely wro...,Skyfall,1807,http://ia.media-imdb.com/images/M/MV5BMjAyODkz...,68,"Action, Thriller",tt1074638,2012,English
4,Against medical advice and without the knowled...,Silver Linings Playbook,1828,http://ia.media-imdb.com/images/M/MV5BMTM2MTI5...,68,"Comedy, Drama, Romance",tt1045658,2012,English
5,A shy senior and a down-to-earth junior fall i...,The First Time,1538,http://ia.media-imdb.com/images/M/MV5BMjMxNDI1...,60,"Comedy, Drama, Romance",tt1763303,2012,English
6,"In California, the former Navy SEAL Chon and h...",Savages,2683,http://ia.media-imdb.com/images/M/MV5BMTk0ODIy...,55,"Crime, Drama, Thriller",tt1615065,2012,English
7,Meet the Borgens. William Borgens is an acclai...,Stuck in Love,1832,http://ia.media-imdb.com/images/M/MV5BMTU1NzI5...,63,"Comedy, Drama, Romance",tt2205697,2012,English
8,"In 1874, in the Imperial Russia, the aristocra...",Anna Karenina,2094,http://ia.media-imdb.com/images/M/MV5BMTU0NDgx...,56,"Drama, Romance",tt1781769,2012,English
9,"In the 1960s, Richard Kuklinski is working as ...",The Iceman,1859,http://ia.media-imdb.com/images/M/MV5BNDQyMjM5...,59,"Biography, Crime, Drama",tt1491044,2012,English
10,The sunrise blinds the early risers of the cit...,Broken Ledge,2718,http://ia.media-imdb.com/images/M/MV5BMTcyMzYz...,87,Drama,tt2508268,2012,English
11,A mysterious traveler infiltrates a dangerous ...,In the Realms of Madness,2718,http://ia.media-imdb.com/images/M/MV5BNzA2NzE3...,87,"Drama, Horror",tt2248841,2012,English
12,"In both its story on and off the screen, 'Flan...",Flaneurs,2718,NaN,87,"Drama, Romance",tt2364671,2012,English
13,Hailey is in an unhappy marriage but she devel...,The Start of Something Good,2718,NaN,87,"Drama, Romance",tt2331062,2012,English
14,Yannick has to deal with the haunting by himse...,True Storys of the Ghost House 3 the Demon Phe...,2718,NaN,87,Horror,tt3098520,2012,English
15,Seduced by the haunting beauty of a remote mar...,White Wind,2718,NaN,87,"Drama, Mystery",tt2555620,2012,English
16,A psychotic Iraq War veteran teaches his young...,Thelema the Equinox Diaries,2718,NaN,87,"Drama, Thriller",tt2443106,2012,English
17,A politician receives a message that his mistr...,Home Minister,2718,NaN,87,Drama,tt2923826,2012,English
18,A plot to assassinate the Vice President takes...,Placebo Effect,1752,http://ia.media-imdb.com/images/M/MV5BMTU5Njg1...,52,"Crime, Mystery, Thriller",tt0163154,1998,English
19,Long on the Island is a psychological thriller...,Long on the Island,2718,NaN,87,"Fantasy, Horror",tt2375263,2012,English
20,"Over the course of a single night, Dave and An...",I Did,2718,NaN,87,"Drama, Family",tt2388672,2012,English
21,"""Collaging Film"" is a series of shorts dating ...",Collaging Film,2718,NaN,87,Animation,tt4416372,2012,English
22,Hank lives the quiet life until a mysterious i...,Welcoming Departure,2718,http://ia.media-imdb.com/images/M/MV5BMjE0OTU2...,87,"Comedy, Drama",tt2235809,2012,English
23,The Luckiest Girl on the Lower East Side takes...,The Luckiest Girl on the Lower East Side,2718,NaN,87,Drama,tt1876494,2012,English
24,"Less Lost, is the fictional story of a young m...",Less Lost,1114,http://ia.media-imdb.com/images/M/MV5BMTk3MTg2...,68,"Drama, War",tt2259946,2012,English
25,High school student Aidan loses his girlfriend...,Still Here,2302,NaN,53,Drama,tt2275650,2012,English
26,Best friends Sam and Mike go out on a bender a...,The Hedgehog Dilemma,2718,http://ia.media-imdb.com/images/M/MV5BMTU1NDI3...,87,"Drama, Romance",tt2505274,2012,English
27,Filmed and produced by Australian director Sha...,51 Paintings,2457,http://ia.media-imdb.com/images/M/MV5BMTQyNzU2...,61,Drama,tt2318982,2012,English
28,"Capitalists, revolutionaries, and the people w...",The Adventures of Paul and Marian,2718,NaN,87,"Comedy, Musical, Romance",tt1949593,2012,English
29,Various people who lost loved ones during 9-11...,Above the Fire,2718,http://ia.media-imdb.com/images/M/MV5BMTUzNzc5...,87,Drama,tt2231544,2012,English
...,...,...,...,...,...,...,...,...,...
3359,Prabhavati lives a wealthy lifestyle in India ...,Sneham Kosam,NaN,NaN,6.3,"Family, Action",tt0246240,1999,Telugu
3360,The story of the famous Saint-Poet Manjunatha.,Sri Manjunatha,NaN,NaN,6.7,"Drama, Family, History, Musical",tt0249783,2001,Telugu
3361,Lord Rama's life is one of perfect adherence t...,Sri Rama Rajyam,635,NaN,7.2,Drama,tt1783377,2011,Telugu
3362,Based on the life story of the great devotee-m...,Sri Ramadasu,207,NaN,6.9,"Biography, Musical",tt0459205,2006,Telugu
3363,Josef Stalin rises from his rejection as being...,Stalin,653,http://ia.media-imdb.com/images/M/MV5BMTk5OTQw...,5.6,"Action, Drama",tt0105462,2006,Telugu
3364,"The story of aspiring police officer, Prithvir...",State Rowdy,68,NaN,7.4,"Action, Crime, Drama",tt0246254,1989,Telugu
3365,Aditya lives a middle-classed lifestyle in Aur...,Student No 1,473,NaN,6.7,"Action, Crime, Drama",tt1283956,2001,Telugu
3366,Bantu and Chantu are two close friends and fel...,Style,NaN,NaN,5.8,Musical,tt0306855,2006,Telugu
3367,Amarchandra lives a poor lifestyle in British ...,Subhash Chandra Bose,NaN,NaN,2.9,"Action, Drama, History, Romance, Thriller",tt0459554,2005,Telugu
3368,Frank Darrbo is a hapless fry cook. When his w...,Super,NaN,http://ia.media-imdb.com/images/M/MV5BMTcxMDkx...,5.1,"Action, Comedy, Drama, Mystery, Romance",tt1512235,2005,Telugu
3369,Unable to convince the ruling council of Krypt...,Superman,49,http://ia.media-imdb.com/images/M/MV5BMTI1MjA5...,4.2,"Fantasy, Musical, Sci-Fi",tt0078346,1980,Telugu
3370,A priceless idol is stolen from a temple trave...,Swamy Ra Ra,443,NaN,7.5,Crime,tt2767354,2013,Telugu
3371,"The story of a classical singer, who finds it ...",Swathi Kiranam,NaN,NaN,7.8,"Family, Musical, Drama",tt0250012,1992,Telugu
3372,"Ravindranath Tagore, A physics professor forms...",Tagore,861,NaN,7.6,"Action, Drama",tt0361037,2003,Telugu
3373,"Raja is a small-time outlaw, whose daring anti...",Takkari Donga,644,NaN,6.9,"Action, Adventure, Western",tt0307541,2002,Telugu
3374,The story of an Indian Freedom fighter who fou...,Tandra Paparayudu,61,NaN,8,"Action, Biography, Drama, History",tt0253784,1986,Telugu
3375,"Raghu, a business tycoon, is driving through a...",Tarzan Sundari,7,NaN,6,"Action, Adventure, Fantasy, Musical",tt2735328,1983,Telugu
3376,A man reconsiders his ideas about love in the ...,Teen Maar,909,NaN,5.8,"Comedy, Drama, Romance",tt1889440,2011,Telugu
3377,Daya (NTR) is a fully corrupted police officer...,Temper,"1,331",NaN,8.1,"Action, Drama",tt4442758,2015,Telugu
3378,Classic about the life story of Carnatic Music...,Thyagayya,NaN,NaN,7.3,"Family, History, Musical",tt0246277,1946,Telugu
3379,"A romantic entertainer between a ""bava"" and a ...",Uyyala Jampala,NaN,NaN,7.5,"Drama, Family, Romance",tt3290676,2013,Telugu
3380,About to re-locate to the U.S. but refusing to...,Varudu,438,NaN,3.5,"Action, Crime, Drama, Thriller",tt1582637,2010,Telugu
3381,Cable Raju is a slum dweller who works as a ca...,Vedam,"2,015",NaN,8.1,Drama,tt1649431,2010,Telugu
3382,A simple train journey to Tirupathi goes horri...,Venkatadri Express,79,NaN,7.5,"Adventure, Comedy",tt3573040,2013,Telugu
3383,Venky and his friends are accused of murdering...,Venky,NaN,NaN,7.1,"Mystery, Romance",tt0417229,2004,Telugu
3384,"Vikram Rathod, A sincere Police man joins with...",Vikramarkudu,"1,158",NaN,7.5,"Action, Comedy, Crime, Thriller",tt0858492,2006,Telugu
3385,After an eventful train trip on the Visakha/Ra...,Visakha Express,43,NaN,4.5,"Crime, Drama, Mystery, Thriller",tt1285147,2008,Telugu
3386,"Mahi is a beautiful wealthy heiress, but her f...",Yamadonga,"1,316",NaN,7.3,"Action, Comedy, Fantasy, Romance",tt0924317,2007,Telugu
3387,Yevade Subramanyam has wrapped its shooting an...,Yevade Subramanyam,188,NaN,7.9,"Adventure, Comedy, Drama",tt4515070,2015,Telugu
3388,Sathya (Allu Arjun) returns from a coma to tak...,Yevadu,"3,966",NaN,4.6,"Action, Thriller",tt2211173,2014,Telugu

In [187]:
#==================  2b & 2d  ======================
#Counting number of occurances of each Genre using groupby function. 
#That sorts as well
a = pd.DataFrame(dataIMDB.groupby(dataIMDB.Genre).Plot.nunique())
#Making the index the Genre columns
a['Genre'] = a.index
#Renaming the columns in the data frame
a.columns = ['Counts', 'Genre']
#Resetting the indexes
a.index = range(len(a))
#Realigning the columns
a = a[['Genre', 'Counts']]
#Inserting the index column
a.insert(0, 'ID', range(1, 1+len(a)))
uniq_genre = a
#Freeing up space
del a
uniq_genre

      ID                                              Genre  Counts
0      1                                             Action      41
1      2                                  Action, Adventure       3
2      3  Action, Adventure, Biography, Drama, History, ...       1
3      4          Action, Adventure, Comedy, Crime, Musical       1
4      5                   Action, Adventure, Comedy, Drama       1
5      6  Action, Adventure, Comedy, Drama, Fantasy, Mus...       1
6      7  Action, Adventure, Comedy, Drama, Musical, Thr...       1
7      8                  Action, Adventure, Comedy, Horror       1
8      9       Action, Adventure, Comedy, Romance, Thriller       1
9     10                    Action, Adventure, Crime, Drama       1
10    11            Action, Adventure, Crime, Drama, Family       1
11    12          Action, Adventure, Crime, Drama, Thriller       5
12    13                           Action, Adventure, Drama      11
13    14                  Action, Adventure, Drama, Fantasy       2
14    15         Action, Adventure, Drama, Sci-Fi, Thriller       1
15    16                 Action, Adventure, Drama, Thriller       1
16    17       Action, Adventure, Fantasy, Horror, Thriller       1
17    18                Action, Adventure, Fantasy, Musical       1
18    19                 Action, Adventure, Romance, Sci-Fi       1
19    20                        Action, Adventure, Thriller       4
20    21                         Action, Adventure, Western       2
21    22          Action, Biography, Crime, Drama, Thriller       1
22    23          Action, Biography, Crime, Sport, Thriller       1
23    24                  Action, Biography, Drama, History       1
24    25                         Action, Biography, History       1
25    26                                     Action, Comedy      17
26    27                       Action, Comedy, Crime, Drama       1
27    28     Action, Comedy, Crime, Drama, Musical, Romance       1
28    29             Action, Comedy, Crime, Drama, Thriller       2
29    30            Action, Comedy, Crime, Musical, Romance       1
..   ...                                                ...     ...
219  220                           Fantasy, Musical, Sci-Fi       1
220  221                                   Fantasy, Romance       2
221  222                                            History      10
222  223                                   History, Musical       1
223  224                                             Horror     115
224  225                                  Horror, Adventure       1
225  226                          Horror, Mystery, Thriller      29
226  227                          Horror, Romance, Thriller       4
227  228                                   Horror, Thriller      68
228  229                                     Music, Musical       2
229  230                                            Musical      21
230  231                           Musical, Comedy, Romance       1
231  232                                     Musical, Drama       1
232  233                        Musical, Drama, Action, War       1
233  234                  Musical, Drama, Adventure, Comedy       1
234  235                             Musical, Drama, Family       1
235  236                            Musical, Drama, Romance       1
236  237                         Musical, Mystery, Thriller       1
237  238                                   Musical, Romance       3
238  239                    Musical, Romance, Action, Drama       1
239  240                            Musical, Romance, Drama       1
240  241                    Musical, Romance, Drama, Family       1
241  242                                            Mystery      21
242  243                                   Mystery, Romance       2
243  244                                  Mystery, Thriller      27
244  245                                    Romance, Sci-Fi       1
245  246                                             Sci-Fi      31
246  247                                              Sport      14
247  248                                  Thriller, Mystery       1
248  249                                War, Drama, Romance       1

[249 rows x 3 columns]

In [205]:
#==========Another way to do 2b & 2d ===================
a = dataIMDB.Genre.value_counts()
a = pd.DataFrame(a)
a['Genres'] = a.index
a.columns = ['Counts', 'Genre']
a.index = range(1, 1+len(a))
a = a.sort_values(by='Genre')
a.index = range(len(a))
a = a[['Genre', 'Counts']]
a.insert(0, 'ID', range(1, 1+len(a)))
a

      ID                                              Genre  Counts
0      1                                             Action      41
1      2                                  Action, Adventure       3
2      3  Action, Adventure, Biography, Drama, History, ...       1
3      4          Action, Adventure, Comedy, Crime, Musical       1
4      5                   Action, Adventure, Comedy, Drama       1
5      6  Action, Adventure, Comedy, Drama, Fantasy, Mus...       1
6      7  Action, Adventure, Comedy, Drama, Musical, Thr...       1
7      8                  Action, Adventure, Comedy, Horror       1
8      9       Action, Adventure, Comedy, Romance, Thriller       1
9     10                    Action, Adventure, Crime, Drama       1
10    11            Action, Adventure, Crime, Drama, Family       1
11    12          Action, Adventure, Crime, Drama, Thriller       5
12    13                           Action, Adventure, Drama      11
13    14                  Action, Adventure, Drama, Fantasy       2
14    15         Action, Adventure, Drama, Sci-Fi, Thriller       1
15    16                 Action, Adventure, Drama, Thriller       1
16    17       Action, Adventure, Fantasy, Horror, Thriller       1
17    18                Action, Adventure, Fantasy, Musical       1
18    19                 Action, Adventure, Romance, Sci-Fi       1
19    20                        Action, Adventure, Thriller       4
20    21                         Action, Adventure, Western       2
21    22          Action, Biography, Crime, Drama, Thriller       1
22    23          Action, Biography, Crime, Sport, Thriller       1
23    24                  Action, Biography, Drama, History       1
24    25                         Action, Biography, History       1
25    26                                     Action, Comedy      17
26    27                       Action, Comedy, Crime, Drama       1
27    28     Action, Comedy, Crime, Drama, Musical, Romance       1
28    29             Action, Comedy, Crime, Drama, Thriller       2
29    30            Action, Comedy, Crime, Musical, Romance       1
..   ...                                                ...     ...
219  220                           Fantasy, Musical, Sci-Fi       1
220  221                                   Fantasy, Romance       2
221  222                                            History      10
222  223                                   History, Musical       1
223  224                                             Horror     115
224  225                                  Horror, Adventure       1
225  226                          Horror, Mystery, Thriller      29
226  227                          Horror, Romance, Thriller       4
227  228                                   Horror, Thriller      68
228  229                                     Music, Musical       2
229  230                                            Musical      21
230  231                           Musical, Comedy, Romance       1
231  232                                     Musical, Drama       1
232  233                        Musical, Drama, Action, War       1
233  234                  Musical, Drama, Adventure, Comedy       1
234  235                             Musical, Drama, Family       1
235  236                            Musical, Drama, Romance       1
236  237                         Musical, Mystery, Thriller       1
237  238                                   Musical, Romance       3
238  239                    Musical, Romance, Action, Drama       1
239  240                            Musical, Romance, Drama       1
240  241                    Musical, Romance, Drama, Family       1
241  242                                            Mystery      21
242  243                                   Mystery, Romance       2
243  244                                  Mystery, Thriller      27
244  245                                    Romance, Sci-Fi       1
245  246                                             Sci-Fi      31
246  247                                              Sport      14
247  248                                  Thriller, Mystery       1
248  249                                War, Drama, Romance       1

[249 rows x 3 columns]

In [206]:
dataIMDB.describe()

,Plot,Title,imdbVotes,Poster,imdbRating,Genre,imdbID,Year,Language
count,3389,3389,3334,1836,3388,3389,3389,3389,3389
unique,3382,3383,904,1782,87,249,3383,89,4
top,Free-thinking Johnny Case finds himself betrot...,Josh,2718,http://i.media-imdb.com/images/SF1f0a42ee1aa08...,87,Drama,tt0151150,2014,English
freq,2,2,1702,52,1702,689,2,1031,2932

In [233]:
#==================  2c  ======================
#Copying data to avoid rerunning the kernel
x = dataIMDB
#Converting imdbRating & imdbVotes from str type to numeric type.
#errors = coerce - forces uncompatible data to be parsed to NaN, and not raise an error
#astype() gives errors. For error argument, it has only 'ignore' & 'raise' values. So doesn't work
x.imdbRating = pd.to_numeric(x.imdbRating, errors='coerce')
x.imdbVotes = pd.to_numeric(x.imdbVotes, errors='coerce')
type(x.imdbRating[2]), type(x.imdbVotes)

(numpy.float64, pandas.core.series.Series)

In [238]:
#=================  2e  =======================
x['SquaredDiff'] = (x.imdbRating - x.imdbVotes)**2
x

,Plot,Title,imdbVotes,Poster,imdbRating,Genre,imdbID,Year,Language,SquaredDiff
0,Despite his tarnished reputation after the eve...,The Dark Knight Rises,2679.0,http://ia.media-imdb.com/images/M/MV5BMTk4ODQz...,75.0,"Action, Thriller",tt1345836,2012,English,6780816.00
1,"Based on the novel written by Stephen Chbosky,...",The Perks of Being a Wallflower,1270.0,http://ia.media-imdb.com/images/M/MV5BMzIxOTQy...,71.0,"Drama, Romance",tt1659337,2012,English,1437601.00
2,Mike Lane is a thirty-year old living in Tampa...,Magic Mike,2580.0,http://ia.media-imdb.com/images/M/MV5BMTQzMDMz...,51.0,"Comedy, Drama",tt1915581,2012,English,6395841.00
3,When Bond's latest assignment goes gravely wro...,Skyfall,1807.0,http://ia.media-imdb.com/images/M/MV5BMjAyODkz...,68.0,"Action, Thriller",tt1074638,2012,English,3024121.00
4,Against medical advice and without the knowled...,Silver Linings Playbook,1828.0,http://ia.media-imdb.com/images/M/MV5BMTM2MTI5...,68.0,"Comedy, Drama, Romance",tt1045658,2012,English,3097600.00
5,A shy senior and a down-to-earth junior fall i...,The First Time,1538.0,http://ia.media-imdb.com/images/M/MV5BMjMxNDI1...,60.0,"Comedy, Drama, Romance",tt1763303,2012,English,2184484.00
6,"In California, the former Navy SEAL Chon and h...",Savages,2683.0,http://ia.media-imdb.com/images/M/MV5BMTk0ODIy...,55.0,"Crime, Drama, Thriller",tt1615065,2012,English,6906384.00
7,Meet the Borgens. William Borgens is an acclai...,Stuck in Love,1832.0,http://ia.media-imdb.com/images/M/MV5BMTU1NzI5...,63.0,"Comedy, Drama, Romance",tt2205697,2012,English,3129361.00
8,"In 1874, in the Imperial Russia, the aristocra...",Anna Karenina,2094.0,http://ia.media-imdb.com/images/M/MV5BMTU0NDgx...,56.0,"Drama, Romance",tt1781769,2012,English,4153444.00
9,"In the 1960s, Richard Kuklinski is working as ...",The Iceman,1859.0,http://ia.media-imdb.com/images/M/MV5BNDQyMjM5...,59.0,"Biography, Crime, Drama",tt1491044,2012,English,3240000.00
10,The sunrise blinds the early risers of the cit...,Broken Ledge,2718.0,http://ia.media-imdb.com/images/M/MV5BMTcyMzYz...,87.0,Drama,tt2508268,2012,English,6922161.00
11,A mysterious traveler infiltrates a dangerous ...,In the Realms of Madness,2718.0,http://ia.media-imdb.com/images/M/MV5BNzA2NzE3...,87.0,"Drama, Horror",tt2248841,2012,English,6922161.00
12,"In both its story on and off the screen, 'Flan...",Flaneurs,2718.0,NaN,87.0,"Drama, Romance",tt2364671,2012,English,6922161.00
13,Hailey is in an unhappy marriage but she devel...,The Start of Something Good,2718.0,NaN,87.0,"Drama, Romance",tt2331062,2012,English,6922161.00
14,Yannick has to deal with the haunting by himse...,True Storys of the Ghost House 3 the Demon Phe...,2718.0,NaN,87.0,Horror,tt3098520,2012,English,6922161.00
15,Seduced by the haunting beauty of a remote mar...,White Wind,2718.0,NaN,87.0,"Drama, Mystery",tt2555620,2012,English,6922161.00
16,A psychotic Iraq War veteran teaches his young...,Thelema the Equinox Diaries,2718.0,NaN,87.0,"Drama, Thriller",tt2443106,2012,English,6922161.00
17,A politician receives a message that his mistr...,Home Minister,2718.0,NaN,87.0,Drama,tt2923826,2012,English,6922161.00
18,A plot to assassinate the Vice President takes...,Placebo Effect,1752.0,http://ia.media-imdb.com/images/M/MV5BMTU5Njg1...,52.0,"Crime, Mystery, Thriller",tt0163154,1998,English,2890000.00
19,Long on the Island is a psychological thriller...,Long on the Island,2718.0,NaN,87.0,"Fantasy, Horror",tt2375263,2012,English,6922161.00
20,"Over the course of a single night, Dave and An...",I Did,2718.0,NaN,87.0,"Drama, Family",tt2388672,2012,English,6922161.00
21,"""Collaging Film"" is a series of shorts dating ...",Collaging Film,2718.0,NaN,87.0,Animation,tt4416372,2012,English,6922161.00
22,Hank lives the quiet life until a mysterious i...,Welcoming Departure,2718.0,http://ia.media-imdb.com/images/M/MV5BMjE0OTU2...,87.0,"Comedy, Drama",tt2235809,2012,English,6922161.00
23,The Luckiest Girl on the Lower East Side takes...,The Luckiest Girl on the Lower East Side,2718.0,NaN,87.0,Drama,tt1876494,2012,English,6922161.00
24,"Less Lost, is the fictional story of a young m...",Less Lost,1114.0,http://ia.media-imdb.com/images/M/MV5BMTk3MTg2...,68.0,"Drama, War",tt2259946,2012,English,1094116.00
25,High school student Aidan loses his girlfriend...,Still Here,2302.0,NaN,53.0,Drama,tt2275650,2012,English,5058001.00
26,Best friends Sam and Mike go out on a bender a...,The Hedgehog Dilemma,2718.0,http://ia.media-imdb.com/images/M/MV5BMTU1NDI3...,87.0,"Drama, Romance",tt2505274,2012,English,6922161.00
27,Filmed and produced by Australian director Sha...,51 Paintings,2457.0,http://ia.media-imdb.com/images/M/MV5BMTQyNzU2...,61.0,Drama,tt2318982,2012,English,5740816.00
28,"Capitalists, revolutionaries, and the people w...",The Adventures of Paul and Marian,2718.0,NaN,87.0,"Comedy, Musical, Romance",tt1949593,2012,English,6922161.00
29,Various people who lost loved ones during 9-11...,Above the Fire,2718.0,http://ia.media-imdb.com/images/M/MV5BMTUzNzc5...,87.0,Drama,tt2231544,2012,English,6922161.00
...,...,...,...,...,...,...,...,...,...,...
3359,Prabhavati lives a wealthy lifestyle in India ...,Sneham Kosam,NaN,NaN,6.3,"Family, Action",tt0246240,1999,Telugu,NaN
3360,The story of the famous Saint-Poet Manjunatha.,Sri Manjunatha,NaN,NaN,6.7,"Drama, Family, History, Musical",tt0249783,2001,Telugu,NaN
3361,Lord Rama's life is one of perfect adherence t...,Sri Rama Rajyam,635.0,NaN,7.2,Drama,tt1783377,2011,Telugu,394132.84
3362,Based on the life story of the great devotee-m...,Sri Ramadasu,207.0,NaN,6.9,"Biography, Musical",tt0459205,2006,Telugu,40040.01
3363,Josef Stalin rises from his rejection as being...,Stalin,653.0,http://ia.media-imdb.com/images/M/MV5BMTk5OTQw...,5.6,"Action, Drama",tt0105462,2006,Telugu,419126.76
3364,"The story of aspiring police officer, Prithvir...",State Rowdy,68.0,NaN,7.4,"Action, Crime, Drama",tt0246254,1989,Telugu,3672.36
3365,Aditya lives a middle-classed lifestyle in Aur...,Student No 1,473.0,NaN,6.7,"Action, Crime, Drama",tt1283956,2001,Telugu,217435.69
3366,Bantu and Chantu are two close friends and fel...,Style,NaN,NaN,5.8,Musical,tt0306855,2006,Telugu,NaN
3367,Amarchandra lives a poor lifestyle in British ...,Subhash Chandra Bose,NaN,NaN,2.9,"Action, Drama, History, Romance, Thriller",tt0459554,2005,Telugu,NaN
3368,Frank Darrbo is a hapless fry cook. When his w...,Super,NaN,http://ia.media-imdb.com/images/M/MV5BMTcxMDkx...,5.1,"Action, Comedy, Drama, Mystery, Romance",tt1512235,2005,Telugu,NaN
3369,Unable to convince the ruling council of Krypt...,Superman,49.0,http://ia.media-imdb.com/images/M/MV5BMTI1MjA5...,4.2,"Fantasy, Musical, Sci-Fi",tt0078346,1980,Telugu,2007.04
3370,A priceless idol is stolen from a temple trave...,Swamy Ra Ra,443.0,NaN,7.5,Crime,tt2767354,2013,Telugu,189660.25
3371,"The story of a classical singer, who finds it ...",Swathi Kiranam,NaN,NaN,7.8,"Family, Musical, Drama",tt0250012,1992,Telugu,NaN
3372,"Ravindranath Tagore, A physics professor forms...",Tagore,861.0,NaN,7.6,"Action, Drama",tt0361037,2003,Telugu,728291.56
3373,"Raja is a small-time outlaw, whose daring anti...",Takkari Donga,644.0,NaN,6.9,"Action, Adventure, Western",tt0307541,2002,Telugu,405896.41
3374,The story of an Indian Freedom fighter who fou...,Tandra Paparayudu,61.0,NaN,8.0,"Action, Biography, Drama, History",tt0253784,1986,Telugu,2809.00
3375,"Raghu, a business tycoon, is driving through a...",Tarzan Sundari,7.0,NaN,6.0,"Action, Adventure, Fantasy, Musical",tt2735328,1983,Telugu,1.00
3376,A man reconsiders his ideas about love in the ...,Teen Maar,909.0,NaN,5.8,"Comedy, Drama, Romance",tt1889440,2011,Telugu,815770.24
3377,Daya (NTR) is a fully corrupted police officer...,Temper,NaN,NaN,8.1,"Action, Drama",tt4442758,2015,Telugu,NaN
3378,Classic about the life story of Carnatic Music...,Thyagayya,NaN,NaN,7.3,"Family, History, Musical",tt0246277,1946,Telugu,NaN
3379,"A romantic entertainer between a ""bava"" and a ...",Uyyala Jampala,NaN,NaN,7.5,"Drama, Family, Romance",tt3290676,2013,Telugu,NaN
3380,About to re-locate to the U.S. but refusing to...,Varudu,438.0,NaN,3.5,"Action, Crime, Drama, Thriller",tt1582637,2010,Telugu,188790.25
3381,Cable Raju is a slum dweller who works as a ca...,Vedam,NaN,NaN,8.1,Drama,tt1649431,2010,Telugu,NaN
3382,A simple train journey to Tirupathi goes horri...,Venkatadri Express,79.0,NaN,7.5,"Adventure, Comedy",tt3573040,2013,Telugu,5112.25
3383,Venky and his friends are accused of murdering...,Venky,NaN,NaN,7.1,"Mystery, Romance",tt0417229,2004,Telugu,NaN
3384,"Vikram Rathod, A sincere Police man joins with...",Vikramarkudu,NaN,NaN,7.5,"Action, Comedy, Crime, Thriller",tt0858492,2006,Telugu,NaN
3385,After an eventful train trip on the Visakha/Ra...,Visakha Express,43.0,NaN,4.5,"Crime, Drama, Mystery, Thriller",tt1285147,2008,Telugu,1482.25
3386,"Mahi is a beautiful wealthy heiress, but her f...",Yamadonga,NaN,NaN,7.3,"Action, Comedy, Fantasy, Romance",tt0924317,2007,Telugu,NaN
3387,Yevade Subramanyam has wrapped its shooting an...,Yevade Subramanyam,188.0,NaN,7.9,"Adventure, Comedy, Drama",tt4515070,2015,Telugu,32436.01
3388,Sathya (Allu Arjun) returns from a coma to tak...,Yevadu,NaN,NaN,4.6,"Action, Thriller",tt2211173,2014,Telugu,NaN

In [246]:
x = x.astype(object)
type(x.Language[1])

str

In [248]:
#==============  2c  ==============
#Converting Language from categorical to numeric type using LabelEncoder
from sklearn.preprocessing import LabelEncoder
lblenc = LabelEncoder()
x.Language = lblenc.fit_transform(x.Language)
x

,Plot,Title,imdbVotes,Poster,imdbRating,Genre,imdbID,Year,Language,SquaredDiff
0,Despite his tarnished reputation after the eve...,The Dark Knight Rises,2679,http://ia.media-imdb.com/images/M/MV5BMTk4ODQz...,75,"Action, Thriller",tt1345836,2012,1,6.78082e+06
1,"Based on the novel written by Stephen Chbosky,...",The Perks of Being a Wallflower,1270,http://ia.media-imdb.com/images/M/MV5BMzIxOTQy...,71,"Drama, Romance",tt1659337,2012,0,1.4376e+06
2,Mike Lane is a thirty-year old living in Tampa...,Magic Mike,2580,http://ia.media-imdb.com/images/M/MV5BMTQzMDMz...,51,"Comedy, Drama",tt1915581,2012,0,6.39584e+06
3,When Bond's latest assignment goes gravely wro...,Skyfall,1807,http://ia.media-imdb.com/images/M/MV5BMjAyODkz...,68,"Action, Thriller",tt1074638,2012,0,3.02412e+06
4,Against medical advice and without the knowled...,Silver Linings Playbook,1828,http://ia.media-imdb.com/images/M/MV5BMTM2MTI5...,68,"Comedy, Drama, Romance",tt1045658,2012,0,3.0976e+06
5,A shy senior and a down-to-earth junior fall i...,The First Time,1538,http://ia.media-imdb.com/images/M/MV5BMjMxNDI1...,60,"Comedy, Drama, Romance",tt1763303,2012,0,2.18448e+06
6,"In California, the former Navy SEAL Chon and h...",Savages,2683,http://ia.media-imdb.com/images/M/MV5BMTk0ODIy...,55,"Crime, Drama, Thriller",tt1615065,2012,0,6.90638e+06
7,Meet the Borgens. William Borgens is an acclai...,Stuck in Love,1832,http://ia.media-imdb.com/images/M/MV5BMTU1NzI5...,63,"Comedy, Drama, Romance",tt2205697,2012,0,3.12936e+06
8,"In 1874, in the Imperial Russia, the aristocra...",Anna Karenina,2094,http://ia.media-imdb.com/images/M/MV5BMTU0NDgx...,56,"Drama, Romance",tt1781769,2012,0,4.15344e+06
9,"In the 1960s, Richard Kuklinski is working as ...",The Iceman,1859,http://ia.media-imdb.com/images/M/MV5BNDQyMjM5...,59,"Biography, Crime, Drama",tt1491044,2012,0,3.24e+06
10,The sunrise blinds the early risers of the cit...,Broken Ledge,2718,http://ia.media-imdb.com/images/M/MV5BMTcyMzYz...,87,Drama,tt2508268,2012,0,6.92216e+06
11,A mysterious traveler infiltrates a dangerous ...,In the Realms of Madness,2718,http://ia.media-imdb.com/images/M/MV5BNzA2NzE3...,87,"Drama, Horror",tt2248841,2012,0,6.92216e+06
12,"In both its story on and off the screen, 'Flan...",Flaneurs,2718,NaN,87,"Drama, Romance",tt2364671,2012,0,6.92216e+06
13,Hailey is in an unhappy marriage but she devel...,The Start of Something Good,2718,NaN,87,"Drama, Romance",tt2331062,2012,0,6.92216e+06
14,Yannick has to deal with the haunting by himse...,True Storys of the Ghost House 3 the Demon Phe...,2718,NaN,87,Horror,tt3098520,2012,0,6.92216e+06
15,Seduced by the haunting beauty of a remote mar...,White Wind,2718,NaN,87,"Drama, Mystery",tt2555620,2012,0,6.92216e+06
16,A psychotic Iraq War veteran teaches his young...,Thelema the Equinox Diaries,2718,NaN,87,"Drama, Thriller",tt2443106,2012,0,6.92216e+06
17,A politician receives a message that his mistr...,Home Minister,2718,NaN,87,Drama,tt2923826,2012,0,6.92216e+06
18,A plot to assassinate the Vice President takes...,Placebo Effect,1752,http://ia.media-imdb.com/images/M/MV5BMTU5Njg1...,52,"Crime, Mystery, Thriller",tt0163154,1998,0,2.89e+06
19,Long on the Island is a psychological thriller...,Long on the Island,2718,NaN,87,"Fantasy, Horror",tt2375263,2012,0,6.92216e+06
20,"Over the course of a single night, Dave and An...",I Did,2718,NaN,87,"Drama, Family",tt2388672,2012,0,6.92216e+06
21,"""Collaging Film"" is a series of shorts dating ...",Collaging Film,2718,NaN,87,Animation,tt4416372,2012,0,6.92216e+06
22,Hank lives the quiet life until a mysterious i...,Welcoming Departure,2718,http://ia.media-imdb.com/images/M/MV5BMjE0OTU2...,87,"Comedy, Drama",tt2235809,2012,0,6.92216e+06
23,The Luckiest Girl on the Lower East Side takes...,The Luckiest Girl on the Lower East Side,2718,NaN,87,Drama,tt1876494,2012,0,6.92216e+06
24,"Less Lost, is the fictional story of a young m...",Less Lost,1114,http://ia.media-imdb.com/images/M/MV5BMTk3MTg2...,68,"Drama, War",tt2259946,2012,0,1.09412e+06
25,High school student Aidan loses his girlfriend...,Still Here,2302,NaN,53,Drama,tt2275650,2012,0,5.058e+06
26,Best friends Sam and Mike go out on a bender a...,The Hedgehog Dilemma,2718,http://ia.media-imdb.com/images/M/MV5BMTU1NDI3...,87,"Drama, Romance",tt2505274,2012,0,6.92216e+06
27,Filmed and produced by Australian director Sha...,51 Paintings,2457,http://ia.media-imdb.com/images/M/MV5BMTQyNzU2...,61,Drama,tt2318982,2012,0,5.74082e+06
28,"Capitalists, revolutionaries, and the people w...",The Adventures of Paul and Marian,2718,NaN,87,"Comedy, Musical, Romance",tt1949593,2012,0,6.92216e+06
29,Various people who lost loved ones during 9-11...,Above the Fire,2718,http://ia.media-imdb.com/images/M/MV5BMTUzNzc5...,87,Drama,tt2231544,2012,0,6.92216e+06
...,...,...,...,...,...,...,...,...,...,...
3359,Prabhavati lives a wealthy lifestyle in India ...,Sneham Kosam,NaN,NaN,6.3,"Family, Action",tt0246240,1999,3,NaN
3360,The story of the famous Saint-Poet Manjunatha.,Sri Manjunatha,NaN,NaN,6.7,"Drama, Family, History, Musical",tt0249783,2001,3,NaN
3361,Lord Rama's life is one of perfect adherence t...,Sri Rama Rajyam,635,NaN,7.2,Drama,tt1783377,2011,3,394133
3362,Based on the life story of the great devotee-m...,Sri Ramadasu,207,NaN,6.9,"Biography, Musical",tt0459205,2006,3,40040
3363,Josef Stalin rises from his rejection as being...,Stalin,653,http://ia.media-imdb.com/images/M/MV5BMTk5OTQw...,5.6,"Action, Drama",tt0105462,2006,3,419127
3364,"The story of aspiring police officer, Prithvir...",State Rowdy,68,NaN,7.4,"Action, Crime, Drama",tt0246254,1989,3,3672.36
3365,Aditya lives a middle-classed lifestyle in Aur...,Student No 1,473,NaN,6.7,"Action, Crime, Drama",tt1283956,2001,3,217436
3366,Bantu and Chantu are two close friends and fel...,Style,NaN,NaN,5.8,Musical,tt0306855,2006,3,NaN
3367,Amarchandra lives a poor lifestyle in British ...,Subhash Chandra Bose,NaN,NaN,2.9,"Action, Drama, History, Romance, Thriller",tt0459554,2005,3,NaN
3368,Frank Darrbo is a hapless fry cook. When his w...,Super,NaN,http://ia.media-imdb.com/images/M/MV5BMTcxMDkx...,5.1,"Action, Comedy, Drama, Mystery, Romance",tt1512235,2005,3,NaN
3369,Unable to convince the ruling council of Krypt...,Superman,49,http://ia.media-imdb.com/images/M/MV5BMTI1MjA5...,4.2,"Fantasy, Musical, Sci-Fi",tt0078346,1980,3,2007.04
3370,A priceless idol is stolen from a temple trave...,Swamy Ra Ra,443,NaN,7.5,Crime,tt2767354,2013,3,189660
3371,"The story of a classical singer, who finds it ...",Swathi Kiranam,NaN,NaN,7.8,"Family, Musical, Drama",tt0250012,1992,3,NaN
3372,"Ravindranath Tagore, A physics professor forms...",Tagore,861,NaN,7.6,"Action, Drama",tt0361037,2003,3,728292
3373,"Raja is a small-time outlaw, whose daring anti...",Takkari Donga,644,NaN,6.9,"Action, Adventure, Western",tt0307541,2002,3,405896
3374,The story of an Indian Freedom fighter who fou...,Tandra Paparayudu,61,NaN,8,"Action, Biography, Drama, History",tt0253784,1986,3,2809
3375,"Raghu, a business tycoon, is driving through a...",Tarzan Sundari,7,NaN,6,"Action, Adventure, Fantasy, Musical",tt2735328,1983,3,1
3376,A man reconsiders his ideas about love in the ...,Teen Maar,909,NaN,5.8,"Comedy, Drama, Romance",tt1889440,2011,3,815770
3377,Daya (NTR) is a fully corrupted police officer...,Temper,NaN,NaN,8.1,"Action, Drama",tt4442758,2015,3,NaN
3378,Classic about the life story of Carnatic Music...,Thyagayya,NaN,NaN,7.3,"Family, History, Musical",tt0246277,1946,3,NaN
3379,"A romantic entertainer between a ""bava"" and a ...",Uyyala Jampala,NaN,NaN,7.5,"Drama, Family, Romance",tt3290676,2013,3,NaN
3380,About to re-locate to the U.S. but refusing to...,Varudu,438,NaN,3.5,"Action, Crime, Drama, Thriller",tt1582637,2010,3,188790
3381,Cable Raju is a slum dweller who works as a ca...,Vedam,NaN,NaN,8.1,Drama,tt1649431,2010,3,NaN
3382,A simple train journey to Tirupathi goes horri...,Venkatadri Express,79,NaN,7.5,"Adventure, Comedy",tt3573040,2013,3,5112.25
3383,Venky and his friends are accused of murdering...,Venky,NaN,NaN,7.1,"Mystery, Romance",tt0417229,2004,3,NaN
3384,"Vikram Rathod, A sincere Police man joins with...",Vikramarkudu,NaN,NaN,7.5,"Action, Comedy, Crime, Thriller",tt0858492,2006,3,NaN
3385,After an eventful train trip on the Visakha/Ra...,Visakha Express,43,NaN,4.5,"Crime, Drama, Mystery, Thriller",tt1285147,2008,3,1482.25
3386,"Mahi is a beautiful wealthy heiress, but her f...",Yamadonga,NaN,NaN,7.3,"Action, Comedy, Fantasy, Romance",tt0924317,2007,3,NaN
3387,Yevade Subramanyam has wrapped its shooting an...,Yevade Subramanyam,188,NaN,7.9,"Adventure, Comedy, Drama",tt4515070,2015,3,32436
3388,Sathya (Allu Arjun) returns from a coma to tak...,Yevadu,NaN,NaN,4.6,"Action, Thriller",tt2211173,2014,3,NaN

# DONE